### ISSUE TITLE
Stuck on 33% loading

### ISSUE THREAD

**Issue by IzNard** [Ghetto05/GhettosFirearmSDKv2#10]
I installed the newest version of Ghetto Firearm SDK v2 on Blade and Sorcery 12.3, i dont understand the issue because i extracted the mod correctly

**Comment by IzNard** [comment]
I have a pirated version cuz im not spending 20 bucks

**Comment by Ghetto05** [comment]
That would be the issue

**Comment by IzNard** [comment]
Just bought the game and it works ty

**Comment by ShiroKaizaki** [comment]
Hi, I have the same issue but i bought the game so idk what is wrong. I checked the folder is not subfolded and it has the good name. Anyone can help?
